name: Build and Release Image

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Checkout code
      - uses: actions/checkout@v3

      - name: Log in to the Container registry (push-only)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Store last commit's author, message and SHA
        run: |
          echo "Saving local commit details in src/assets/config/version.txt"
          git log -1 > src/assets/config/version.txt
          echo "Saving build date to src/assets/config/ui-build-date.txt"
          date --utc +%FT%TZ > src/assets/config/ui-build-date.txt

      - name: Build EDC-UI image
        uses: docker/build-push-action@v6
        with:
          file: docker/Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            EDC_UI_CONFIGURATION=production
          push: true
          tags: truzzt/mds-edc-ui:latest
